# Generated by Django 4.1 on 2022-09-19 10:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=240)),
                ('title', models.CharField(default='Claims', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFamilies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=240)),
                ('title', models.CharField(default='Product Families', max_length=240)),
            ],
        ),
    ]
