# Generated by Django 4.1 on 2022-09-20 15:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=240)),
                ('title', models.CharField(default='Filter', max_length=240)),
                ('product_families_id', models.CharField(default='', max_length=8)),
                ('claims_id', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
