# Generated by Django 4.1 on 2022-09-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_filters_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='claims_id',
        ),
    ]
