# Generated by Django 4.1 on 2022-09-22 13:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_filters_claims_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=240)),
                ('description', models.CharField(default='', max_length=2400)),
                ('image', models.ImageField(default='images/post_images/default.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
                ('product_families_id', models.CharField(default='', max_length=8)),
                ('claims_id', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
