# Generated by Django 4.1 on 2022-09-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_claims_id_values_filter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='product_families_id',
        ),
    ]
