# Generated by Django 4.1 on 2022-09-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_values_product_families_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='values',
            old_name='filter_id',
            new_name='filters_id',
        ),
    ]
