# Generated by Django 3.1.7 on 2022-11-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20221117_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filters',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='filters',
            name='product_familiy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.productfamilies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='values',
            name='filter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.filters'),
            preserve_default=False,
        ),
    ]
