# Generated by Django 3.1.7 on 2022-11-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20221121_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='product_families_id',
        ),
        migrations.RemoveField(
            model_name='values',
            name='filters_id',
        ),
    ]
