# Generated by Django 3.1.7 on 2022-11-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20221121_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filters',
            old_name='product_familiy',
            new_name='product_family',
        ),
    ]
