# Generated by Django 3.1.7 on 2022-11-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20221121_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=240)),
                ('description', models.CharField(default='', max_length=2048)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.claims')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filters')),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfamilies')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
