# Generated by Django 3.1.7 on 2022-11-21 10:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='post_images/default.jpg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
