# Generated by Django 3.1.7 on 2022-11-30 14:54

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=240)),
                ('content', models.CharField(default='', max_length=2048)),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.page')),
            ],
            options={
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=240)),
                ('content', models.ImageField(default='post_images/default.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.page')),
            ],
            options={
                'ordering': ['page'],
            },
        ),
    ]
